on: [push, workflow_dispatch]

name: hoopR NBA Data trigger

jobs:
    hoopR_nba_data_trigger:
        runs-on: ubuntu-latest
        steps:
            - name: Trigger hoopR NBA Data
              uses: peter-evans/repository-dispatch@v3
              with:
                  token: ${{ secrets.SDV_GH_TOKEN }}
                  repository: sportsdataverse/hoopR-nba-data
                  event-type: daily_nba_data
                  client-payload: '{"ref": "refs/heads/main",
                                    "event_name": "daily_nba_data",
                                    "commit_message": "${{ github.event.head_commit.message }}"
                                    }'
